export * from './block.interface'
export * from './transaction.interface'
export * from './payload.interface'
export * from './pagination.interface'
export * from './pagination-result.interface'
export * from './miner.interface'
export * from './search-result.interface'
export * from './wallet.interface'
